/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package snossoftwaretest;

/**
 *
 * @author fupre3
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 * This class prepares and initializes the necessary SWING GUI 
 * components needed to modify and edit the administrators/super users’ accounts. 
 * It also defines and implements the corresponding methods or/and functions. 
 * to a particular SNOS number belonging to a particular client. 
 * Furthermore: it defines and implements the corresponding methods or/and functions.
 * @author Afam;
 * @see AdminLogin.java,Operator.java
 * @version 1.0 
 */
public class Change_user extends javax.swing.JDialog {

    /**
     * Creates new form Change_user
     */
    //private String user_id;
     private String myid[]=SmsMain.getmyuserid();
      private String InfoLogged="";
    
    public Change_user() {
       // super(parent, modal);
       // this.user_id=m;
       
        initComponents();
        String name= new Reconsoft().RetrieveItem("admin","user_id", myid[1], "user_name");
        if(!myid[1].equals("") && myid[2].equals("super Admin")){
          
          if(name.equals(""))
          {
               JOptionPane.showMessageDialog(null,"There was a problem retrieving your name, \nPlease contact Database Administrator");
          }
          else
          {
             nameTF.setText(name); 
             useridTF.setText(myid[1]);
             useridTF.setEditable(false);
             staTF.setText(myid[2]);
             staTF.setEditable(false);
          }
          
        }
         else{
          nameTF.setText(name);
          useridTF.setText(myid[1]);
          useridTF.setEditable(false);
          staTF.setText(myid[2]);
          staTF.setEditable(true);   
        }
         
    }

    
    
    
    
    
    public void UpdateInforCaller()
 {
     String name =nameTF.getText();
     String user =useridTF.getText();
     String pass = passTF.getText();
     String vpass=vpassTF.getText();
     
     String status=staTF.getText();
     if(name.equals("")||name==null)
     {
         JOptionPane.showMessageDialog(null,"Name field Should not be Empty");
     }
     if(user.equals("")||user==null)
     {
         JOptionPane.showMessageDialog(null,"User id Should not be Empty");
     }else if(pass.equals("")||pass==null)
     {
         JOptionPane.showMessageDialog(null, "Password Should not be Empty");
     }else if(status.equals("")||status==null)
     {
         JOptionPane.showMessageDialog(null, "Status should not be Empty");
     }else
     {
         if(!pass.equals(vpass) )
         {
             //   || pass!=vpass
           JOptionPane.showMessageDialog(null, "Password MisMatch\n please Check you Password");  
         }else{ 
       
         Reconsoft data=new Reconsoft();
         data.updateAdmin(name,user, pass, status);
         JOptionPane.showMessageDialog(null, "User Information Updated Successfully");
        
         this.ResetB();
         }
     }
 }
    
    
    
    public void ResetB()
  {
      nameTF.setText(null);
      useridTF.setText(null);
      passTF.setText(null);
      vpassTF.setText(null);
      staTF.setText(null);
  }  
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        proB = new javax.swing.JButton();
        reB = new javax.swing.JButton();
        passTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        vpassTF = new javax.swing.JPasswordField();
        staTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        useridTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE LOGIN DETAILS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USER ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("STATUS:");

        proB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proB.setText("Process");
        proB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proBActionPerformed(evt);
            }
        });

        reB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reB.setText("Exit");
        reB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("V PASSWORD:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NAME:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(proB)
                        .addGap(54, 54, 54)
                        .addComponent(reB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(staTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(vpassTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(useridTF, javax.swing.GroupLayout.Alignment.LEADING)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vpassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(staTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reB)
                    .addComponent(proB))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proBActionPerformed
        // TODO add your handling code here:
        UpdateInforCaller();
    }//GEN-LAST:event_proBActionPerformed

    private void reBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_reBActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JButton proB;
    private javax.swing.JButton reB;
    private javax.swing.JTextField staTF;
    private javax.swing.JTextField useridTF;
    private javax.swing.JPasswordField vpassTF;
    // End of variables declaration//GEN-END:variables
}
