/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package snossoftwaretest;

import javax.swing.JOptionPane;

/**
 This prepares and initializes the necessary SWING GUI components 
 * needed for the creation of administrators/SNOC software super users  accounts. 
 * It also defines and implements the corresponding methods or/and functions.
 * @author Afam
 * @see AdminLogin.java, Change_user.java
 * @version 1.0 
 */
public class Operator extends javax.swing.JDialog {
private String InfoLogged="";
    /**
     * Creates new form Create_user
     */
    public Operator() {
       
        initComponents();
    }

    
    public void DatabaseSender()
 {
     String userid =useridTF.getText();
      String name =nameTF.getText();
     String pass = passTF.getText();
     String vpass=vpassTF.getText();
     String stat=(String)staCB.getSelectedItem();
     if(name.equals("")||name==null)
     {
         JOptionPane.showMessageDialog(null,"Name Should not be Empty");
     }
     else  if(userid.equals("")||userid==null)
     {
         JOptionPane.showMessageDialog(null,"User id Should not be Empty");
     }else if(pass.equals("")||pass==null)
     {
         JOptionPane.showMessageDialog(null, "Password Should not be Empty");
     }
     else if(vpass.equals("")||vpass==null)
     {
         JOptionPane.showMessageDialog(null, "Verify Password Should not be Empty");
     }
     else if(staCB.getSelectedIndex()==0)
     {
         JOptionPane.showMessageDialog(null, "Status is Not Selected");
     }else
     {
         if(!pass.equals(vpass) )
         {
             //   || pass!=vpass
           JOptionPane.showMessageDialog(null, "Password MisMatch\n please Check you Password");  
         }else{ 
             
              Reconsoft data=new Reconsoft();
             if(!data.CheckIfItemExist("admin","user_id", userid))
             {
              UserInforGet get = new UserInforGet(name,userid,pass,stat);
                if(new Reconsoft().AddOprator(get)==1)
                {
                    this.ResetB();
                    JOptionPane.showMessageDialog(null,"Information Submitted Successfully");
                }
                else
                {
     
                    JOptionPane.showMessageDialog(null,"Information could not be Submitted successfully, Contact the Administrator\n Or Ensure that your Database Server is running");
                }
     
             
               
             }else
             {
               JOptionPane.showMessageDialog(null,"USERID Already Exists\n Please choose another userid");   
             }
       
         
         
         } 
     }
 }
    
   
    public void ResetB()
  {
      nameTF.setText(null);
      useridTF.setText(null);
      passTF.setText(null);
      vpassTF.setText(null);
      staCB.setSelectedIndex(0);
  }  
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        useridTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        staCB = new javax.swing.JComboBox();
        proB = new javax.swing.JButton();
        reB = new javax.swing.JButton();
        passTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        vpassTF = new javax.swing.JPasswordField();
        exitB = new javax.swing.JButton();
        L = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE USER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USER ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("STATUS:");

        staCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose-one", "Super Admin", "Admin", "Data Entry Specialist", "CSO", "Seurity Agent", "others" }));

        proB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proB.setText("Process");
        proB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proBActionPerformed(evt);
            }
        });

        reB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reB.setText("Reset");
        reB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("V PASSWORD:");

        exitB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitB.setText("Exit");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });

        L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L.setText("NAME:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF)
                            .addComponent(staCB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vpassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(reB)
                        .addGap(47, 47, 47)
                        .addComponent(proB)
                        .addGap(66, 66, 66)
                        .addComponent(exitB)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vpassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(staCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reB)
                    .addComponent(proB)
                    .addComponent(exitB))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proBActionPerformed
        // TODO add your handling code here:
        DatabaseSender();
        
    }//GEN-LAST:event_proBActionPerformed

    private void reBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reBActionPerformed
        // TODO add your handling code here:
        this.ResetB();
    }//GEN-LAST:event_reBActionPerformed

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitBActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JButton proB;
    private javax.swing.JButton reB;
    private javax.swing.JComboBox staCB;
    private javax.swing.JTextField useridTF;
    private javax.swing.JPasswordField vpassTF;
    // End of variables declaration//GEN-END:variables
}
