package snossoftwaretest;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tele
 */
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class setup_page extends JFrame {

    private JPanel Main_pan;
    private String path="";
    private File log_file=null;
    private File f1;
    private PatternCheck check = new  PatternCheck();
    
    public setup_page() {
        
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("see.jpg")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     private void Load_Logo()
    {
      JFileChooser chooser=new JFileChooser();
      chooser.addChoosableFileFilter(new ImageFileFilter());
       int returnval=chooser.showOpenDialog(null);
      if(returnval==JFileChooser.APPROVE_OPTION)
	{
	       log_file=chooser.getSelectedFile();
		path=log_file.getPath();
		ImageIcon icon=new ImageIcon(path);
		//labell.setIcon(icon);
                 f1=new File(path);
		//f16.setText(path);
                System.out.println("Logo:"+path);
		//repaint();
	} 
    }
    
     public void Submit_infor()
    {
        String noc_name=this.CheckCo_name(snocTF.getText().trim());
        String loco=this.CheckCo_City(cityTF.getText().trim());
        
        
        Reconsoft dat = new Reconsoft();
      try{
          if(dat.ChecksetupInform()){
              
             JOptionPane.showMessageDialog(null, "Please Setup Information already exists\n if there is any need to edit or replace \nwhat your already have\ncontact teledom Administrator");
             
          }else{
        dat.Addsetup_Inform(noc_name,loco, f1);    
          }
         
      }catch(Exception e){
          System.out.println(e.getMessage() +"setup page");
      }
      
        
    }
    
    
    
    
    
    
    
    
    private class ImageFileFilter extends javax.swing.filechooser.FileFilter{
	public boolean accept(File file)
	{
		if(file.isDirectory()) return false;
		String name=file.getName().toLowerCase();
		return(name.endsWith(".jpg")||name.endsWith(".png")||name.endsWith(".gif"));
	}
	public String getDescription()
	{
		return "Images(*.gif,*.bmp,*jpg,*.png)";
	}
	}
    
    
    
    private String CheckCo_name(String co_name)
    {
        
      if(co_name.equals("") || co_name == null ) 
      {
        JOptionPane.showMessageDialog(null, "SNOC Name should not be Empty"); 
        return null;
      }else if(check.checksetup_infor(co_name)){
         
        
       }else{
          JOptionPane.showMessageDialog(null, "Invalid Character in snoc name Field, Enter letter A-Z\ne.g Teledom"
                  + "International Ltd"); 
        return null;
      } 
       return co_name;
    }
    
    private String CheckCo_City(String co_city)
    {
        
      if(co_city.equals("") || co_city == null ) 
      {
        JOptionPane.showMessageDialog(null, "City should not be Empty"); 
        return null;
      }else if(check.checksetup_infor(co_city)){
         
        
       }else{
          JOptionPane.showMessageDialog(null, "Invalid Character in City Field, Enter letter A-Z\ne.g Lagos"
                  + ",Nigeria."); 
        return null;
      } 
       return co_city;
    }
    
    
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content_pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        snocTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uploadB = new javax.swing.JButton();
        subB = new javax.swing.JButton();
        exitB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Code of sub-components - not shown here
        final ImageIcon icon = new ImageIcon(getClass().getResource("/snossoftwaretest/setup.png"));
        content_pan = new JPanel(){
            protected void paintComponent(Graphics g){
                g.drawImage(icon.getImage(), 0,0, null);
                super.paintComponent(g);
                //super.paintComponent(g);

            }
        };
        content_pan.setLayout(null);

        content_pan.setOpaque(false);

        Main_pan = new JPanel();
        Main_pan.setLayout(new BorderLayout());
        getContentPane().add(Main_pan);
        Main_pan.add(content_pan, BorderLayout.CENTER );

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 110, 205));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SNOC CUSTOMIZATION FORM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Software Title:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("City:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Logo:");

        uploadB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uploadB.setText("Upload Logo");
        uploadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBActionPerformed(evt);
            }
        });

        subB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subB.setText("Submit");
        subB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBActionPerformed(evt);
            }
        });

        exitB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitB.setText("Exit");
        exitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Note: You Have to Provide The Information below before ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("you can use the software.");

        javax.swing.GroupLayout content_panLayout = new javax.swing.GroupLayout(content_pan);
        content_pan.setLayout(content_panLayout);
        content_panLayout.setHorizontalGroup(
            content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_panLayout.createSequentialGroup()
                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(content_panLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(content_panLayout.createSequentialGroup()
                                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cityTF)
                                    .addComponent(snocTF)
                                    .addComponent(uploadB, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, content_panLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(content_panLayout.createSequentialGroup()
                        .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(content_panLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(subB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(content_panLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        content_panLayout.setVerticalGroup(
            content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_panLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snocTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadB)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(content_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subB)
                    .addComponent(exitB))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBActionPerformed
        // TODO add your handling code here:
        Load_Logo();
    }//GEN-LAST:event_uploadBActionPerformed

    private void exitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBActionPerformed

    private void subBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBActionPerformed
        // TODO add your handling code here:
        Submit_infor();
    }//GEN-LAST:event_subBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityTF;
    private javax.swing.JPanel content_pan;
    private javax.swing.JButton exitB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField snocTF;
    private javax.swing.JButton subB;
    private javax.swing.JButton uploadB;
    // End of variables declaration//GEN-END:variables
}
